// Responsive WebP image generated by scripts/make-media.mjs (800w + 1600w, 3:2).
export default function Img({ name, alt, sizes = '(max-width: 760px) 100vw, 50vw', priority = false, className }) {
  return (
    <img
      className={className}
      src={`/img/${name}-1600.webp`}
      srcSet={`/img/${name}-800.webp 800w, /img/${name}-1600.webp 1600w`}
      sizes={sizes}
      width={1600}
      height={1067}
      alt={alt}
      loading={priority ? 'eager' : 'lazy'}
      fetchPriority={priority ? 'high' : undefined}
      decoding="async"
    />
  );
}
